cursor #e3e2e3
cursor_text_color #c1c7cb

foreground            #e3e2e3
background            #121414
selection_foreground  #263237
selection_background  #bbc9cf
url_color             #a9ccdb

color0   #121414
color1   #fb719e
color2   #6ddb79
color3   #fff672
color4   #97bed0
color5   #3a5865
color6   #a9ccdb
color7   #d8e1e5
color8   #838b8e
color9   #ff9fbe
color10  #a5ffaf
color11  #fff9a5
color12  #c2e2f0
color13  #d6f2ff
color14  #e4f7ff
color15  #f8fdff
