return {
	"folke/which-key.nvim",
	event = "VimEnter",
	opts = {
		preset = "modern",
		delay = 300,

		icons = {
			mappings = vim.g.have_nerd_font,
			separator = "  ",
			group = "",
			ellipsis = "…",
			colors = true,
			keys = vim.g.have_nerd_font and {} or {
				Up = "<Up> ",
				Down = "<Down> ",
				Left = "<Left> ",
				Right = "<Right> ",
				C = "<C-…> ",
				M = "<M-…> ",
				D = "<D-…> ",
				S = "<S-…> ",
				CR = "<CR> ",
				Esc = "<Esc> ",
				ScrollWheelDown = "<ScrollWheelDown> ",
				ScrollWheelUp = "<ScrollWheelUp> ",
				NL = "<NL> ",
				BS = "<BS> ",
				Space = "<Space> ",
				Tab = "<Tab> ",
				F1 = "<F1>",
				F2 = "<F2>",
				F3 = "<F3>",
				F4 = "<F4>",
				F5 = "<F5>",
				F6 = "<F6>",
				F7 = "<F7>",
				F8 = "<F8>",
				F9 = "<F9>",
				F10 = "<F10>",
				F11 = "<F11>",
				F12 = "<F12>",
			},
		},

		win = {
			border = "rounded",
			title = true,
			title_pos = "center",
			padding = { 1, 2 },
			wo = {
				winblend = 8,
			},
		},

		layout = {
			spacing = 3,
			align = "center",
		},

		sort = { "group", "alphanum", "order", "mod" },

		spec = {
			{ "<leader>b",  group = "Buffers" },
			{ "<leader>c",  group = "Code",          mode = { "n", "x" } },
			{ "<leader>d",  group = "Document" },
			{ "<leader>f",  group = "Format / Find" },
			{ "<leader>g",  group = "Git Conflicts" },
			{ "<leader>h",  group = "Git Hunks",     mode = { "n", "v" } },
			{ "<leader>q",  group = "Quickfix" },
			{ "<leader>r",  group = "Rename" },
			{ "<leader>s",  group = "Search" },
			{ "<leader>t",  group = "Toggle" },
			{ "<leader>w",  group = "Workspace" },
			{ "<leader>z",  group = "Zoom / Splits" },
		},
	},
}
